apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-v1-deployment
  labels:
    app: marketing-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketing-v1
  template:
    metadata:
      labels:
        app: marketing-v1
    spec:
      containers:
      - name: marketing-v1
        image: emirozbir/marketing:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
